### ISSUE TITLE
ER diagrams in models/README.md are missing

### ISSUE THREAD

**Issue by TuringTux** [colidyre/tutron#2]
The two ER diagrams linked in the file [`tutron/models/README.md`](https://github.com/colidyre/tutron/blob/master/tutron/models/README.md) are missing.

Could someone with access to those diagrams please upload them here too?

Thanks a lot :)

**Comment by colidyre** [comment]
Yes, that's a good idea. Here are the ER diagrams, I will also include them in the README.

![IMG_20180420_155558](https://user-images.githubusercontent.com/15615045/70811522-056d4a00-1dc6-11ea-8432-86e12756f872.jpg)
![IMG_20180420_155605](https://user-images.githubusercontent.com/15615045/70811523-0605e080-1dc6-11ea-804b-232e8b8a1448.jpg)

They're obviously not professional charts. I'm not sure if they're still up to date these days either. Nevertheless, they might be helpful.

**Comment by TuringTux** [comment]
Thank you :) I believe they will be very helpful.
